services:
  - type: web
    name: screenly-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 8000
        sync: false
